name: Nightly
on:
  workflow_dispatch: ~
permissions:
  contents: read
jobs:
  NIGHTLY_MAIN:
    uses: ${{ github.repository}}/.github/workflows/all.yml@main
  NIGHTLY_8.4:
    uses: ${{ github.repository}}/.github/workflows/all.yml@PHP-8.4
